/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        FetchQuote demo = new FetchQuote();
        demo.getRandomQuote("/Users/Ran/code-fellows/java-fundamentals/quotes/src/main/resources/quotes.json");
    }
}
